/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PuntaCanaRouteImport } from './routes/punta-cana'
import { Route as PdfEditorRouteImport } from './routes/pdf-editor'
import { Route as EmberwakeRouteImport } from './routes/emberwake'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoePobbinTradePrivacyRouteImport } from './routes/poe-pobbin-trade.privacy'

const PuntaCanaRoute = PuntaCanaRouteImport.update({
  id: '/punta-cana',
  path: '/punta-cana',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfEditorRoute = PdfEditorRouteImport.update({
  id: '/pdf-editor',
  path: '/pdf-editor',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/pdf-editor.lazy').then((d) => d.Route))
const EmberwakeRoute = EmberwakeRouteImport.update({
  id: '/emberwake',
  path: '/emberwake',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoePobbinTradePrivacyRoute = PoePobbinTradePrivacyRouteImport.update({
  id: '/poe-pobbin-trade/privacy',
  path: '/poe-pobbin-trade/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/emberwake': typeof EmberwakeRoute
  '/pdf-editor': typeof PdfEditorRoute
  '/punta-cana': typeof PuntaCanaRoute
  '/poe-pobbin-trade/privacy': typeof PoePobbinTradePrivacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emberwake': typeof EmberwakeRoute
  '/pdf-editor': typeof PdfEditorRoute
  '/punta-cana': typeof PuntaCanaRoute
  '/poe-pobbin-trade/privacy': typeof PoePobbinTradePrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/emberwake': typeof EmberwakeRoute
  '/pdf-editor': typeof PdfEditorRoute
  '/punta-cana': typeof PuntaCanaRoute
  '/poe-pobbin-trade/privacy': typeof PoePobbinTradePrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/emberwake'
    | '/pdf-editor'
    | '/punta-cana'
    | '/poe-pobbin-trade/privacy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/emberwake'
    | '/pdf-editor'
    | '/punta-cana'
    | '/poe-pobbin-trade/privacy'
  id:
    | '__root__'
    | '/'
    | '/emberwake'
    | '/pdf-editor'
    | '/punta-cana'
    | '/poe-pobbin-trade/privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmberwakeRoute: typeof EmberwakeRoute
  PdfEditorRoute: typeof PdfEditorRoute
  PuntaCanaRoute: typeof PuntaCanaRoute
  PoePobbinTradePrivacyRoute: typeof PoePobbinTradePrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/punta-cana': {
      id: '/punta-cana'
      path: '/punta-cana'
      fullPath: '/punta-cana'
      preLoaderRoute: typeof PuntaCanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-editor': {
      id: '/pdf-editor'
      path: '/pdf-editor'
      fullPath: '/pdf-editor'
      preLoaderRoute: typeof PdfEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emberwake': {
      id: '/emberwake'
      path: '/emberwake'
      fullPath: '/emberwake'
      preLoaderRoute: typeof EmberwakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poe-pobbin-trade/privacy': {
      id: '/poe-pobbin-trade/privacy'
      path: '/poe-pobbin-trade/privacy'
      fullPath: '/poe-pobbin-trade/privacy'
      preLoaderRoute: typeof PoePobbinTradePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmberwakeRoute: EmberwakeRoute,
  PdfEditorRoute: PdfEditorRoute,
  PuntaCanaRoute: PuntaCanaRoute,
  PoePobbinTradePrivacyRoute: PoePobbinTradePrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
